language: node_js
node_js:
  - '4'

addons:
  apt:
    packages:
      - graphicsmagick
      - libcairo2-dev

before_install:
  # Used throughout the bash scripts
  - export LAST_COMMIT_MESSAGE=`git log --format=%B -n 1 $TRAVIS_COMMIT`
  - export RELEASE_VERSION="${LAST_COMMIT_MESSAGE#Release v}"
  - export RELEASE_COMMENT="^Release v[0-9]+\.[0-9]+\.[0-9]+"
  - export RELEASE_BRANCH="^(master|rc-)"
  - export PRERELEASE_BRANCH="^rc-"
  - export SAVAGE_BRANCH="^savage-"
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_BRANCH =~ $RELEASE_BRANCH && $LAST_COMMIT_MESSAGE =~ $RELEASE_COMMENT ]]; then export IS_RELEASE=true; else export IS_RELEASE=false; fi
  - if [[ "$IS_RELEASE" == "true" && $TRAVIS_BRANCH =~ $PRERELEASE_BRANCH ]]; then export IS_PRERELEASE=true; else export IS_PRERELEASE=false; fi

  # The following enable xvfbs so that SlimerJS (a non-headless browser) can be run.
  # They also enable pull requests from forks to use Firefox.
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  # This needs to happen here instead of before_script since some of the node moduules depend on it.
  - gem install sass

  # Make our three scripts executable
  - chmod +x update-skyux.sh
  - chmod +x update-skyux-docs.sh
  - chmod +x update-skyux-releases.sh
  - chmod +x update-skyux-visualtest-results.sh
  - chmod +x run-browserstack-local.sh

  # https://github.com/npm/npm/issues/11283
  - npm set progress=false

# Install a few additional things outside those listed in package.json
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install

# We want deployment failures to fail the build
script: npm test && ./update-skyux.sh && ./update-skyux-releases.sh && ./update-skyux-docs.sh

after_failure: ./update-skyux-visualtest-results.sh

# When a push, only care about the master, rc-, and savage- branches.
# Otherwise anytime we commit to internal branches this would run.
branches:
  only:
    - master
    - /^rc-.*$/
    - /^savage-.*$/

# Cache a few things
cache:
  directories:
    - $HOME/node_modules
    - $HOME/bower_components
    - $HOME/.slimerjs-cache

# Remove some folders from the cache since they arbitrarily change everytime
before_cache:
  - rm -rf $TMPDIR/npm-*
  - find node_modules/\@Blackbaud-PaulCrowder/grunt-phantomcss-slimerjs/node_modules/ -type f -name 'package.json' -delete

notifications:
  slack:
    secure: X3VK9q9hmAcdzxdf8Ba0OHNThYoKKxvFLaDE09s45/75NM38pWQ9iOBJ8GOxYOA0WePzRNEScPxUAFMVKXK0KDbgtcEZ5DdM7kBe7JMo+fB39VLD3L70MVRLdpXnsPZE283GyXmjrmSVg+5gJrSYLwifnvyoqnnRlexL/Hz2JvxbDxdigbgLv8nvgEm5k62RN6kTVFS8aWI7sY1K1aEQdn8yTMy0u1VhBNA3wcFYVpAD1rbyBoSuFhARDVBujTh/RQamngDFLDThKGdCIvf57ierCgLFv6XLFPsviQP5qBMzEbBwu9u0DmOeevUsXUGUPtBSzQN9hBlMU995/n79PoSrlGGmBjISzqwzvp4JNMSDfCh+ne/PX1kIqeFW8egSTVTfCgavbHN4kJvtJZNmi6eDHhFHagSHSBkRgAc6JGvVHVToA1I/u97rcV1nVInhEvUNE6NZ/gkMj0El841ce3IvSZUsFcz/8IoYANxY1LCTmgnF/9GZ3QkKvBU0qhOjsMNnH2zwih38H1Ppqb0/+e+6mlmHpksnKgYwwAS83ZuKzyZbw7I3wyKUEOBCy7wWq45ZjRc74hnrZn/TngHyQ5UXCIlUBn1SjqjyljIKsp85A0lsZLcIEUIsR+7brnMRtMUW5IUaOSow2b52lr4suHG/ShXnUAe1sj2+uxCiy64=
  webhooks:
    - http://sky-savage.cloudapp.net/savage/travis

env:
  global:
    - TMPDIR=$HOME/.slimerjs-cache
